version: "3.3"

services:
  db:
    image: postgres:11.13
    ports:
      - "5433:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: product-service-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
volumes:
  postgres: {}
