### Create product
POST http://localhost:8080/product
Content-Type: application/json

{
  "name": "banana",
  "description": "banana",
  "kcal": 123456
}

### Get product
GET http://localhost:8080/product/6

